### ISSUE TITLE
Makefile doesn't account for alternate Python installations

### ISSUE THREAD

**Issue by Harlantr** [tuchfarber/ThatBeanGame#1]
The makefile assumes you have Python version >3.2 as your default python installation.  If you used "altinstall" to install python, you can only run the necessary commands using `python3 ...` instead of `python ...`.  I had to alter my local instance of the makefile to get the app up and running.

I suggest some sort of check if the user has the correct Python version installed.  If they do, use whichever command will get you to Python 3.X.

**Comment by tuchfarber** [comment]
Where does it make that assumption? The only Python commands are run in `make run` and `make requirements` both of which are supposed to be ran after you have activated the virtual environment. The virtual environment will have your Python version at 3.6 (as seen in the `make env` command). Note: You will need Python3.6 installed on your computer for the `make env` to run correctly.

**Comment by Harlantr** [comment]
Running `make env` either doesn't install the virtual environment in the correct location/format, or `make requirements`/`make run` aren't configured to look in the correct place.

Here's the output of the setup, as I run it from my laptop.

`make env`
```
virtualenv -p `which python3.6` venv
Running virtualenv with interpreter /usr/local/bin/python3.6
Using base prefix '/usr/local'
New python executable in /home/tom/Development/python/ThatBeanGame/venv/bin/python3.6
Also creating executable in /home/tom/Development/python/ThatBeanGame/venv/bin/python
Installing setuptools, pip, wheel...done.
```

`make requirements`
```
pip install -r requirements.txt
Requirement already satisfied: gevent==1.2.2 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 1))
Requirement already satisfied: gevent-websocket==0.10.1 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 2))
Requirement already satisfied: bottle==0.12.13 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 3))
Requirement already satisfied: autopep8==1.3.2 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 4))
Collecting mypy==0.521 (from -r requirements.txt (line 5))
  Using cached mypy-0.521.tar.gz
    Complete output from command python setup.py egg_info:
    ERROR: You need Python 3.2 or later to use mypy.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-jK1dIh/mypy/
Makefile:8: recipe for target 'requirements' failed
make: *** [requirements] Error 1
```

So you can see that even though the virtual environment was set up in the project's directory, the `pip` command is still trying to use python 2.7, which is my default version.

**Comment by tuchfarber** [comment]
So in order for `make requirements` to work, you have to `source` the env first. I would have included this in the make command, except you can't `source` from `make`...

So, order of events:
`make env`
`source venv/bin/activate`
`make requirements`
`make run`

**Comment by Harlantr** [comment]
Ahh, ok.  That makes sense, and it works now.

Can you put setup instructions in the README?

**Comment by tuchfarber** [comment]
Definitely thought I had them in there... Guess I never actually added it. I'll close this out once I add it!

**Comment by tuchfarber** [comment]
README updated with the run commands.

**Comment by Harlantr** [comment]
Thanks beau.
